server:
  port: 8205

mybatis-plus:
  type-enums-package: com.shopping.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  #  数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-activity?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20030111
  rabbitmq:
    host: 192.168.111.100
    port: 5672
    username: itcast
    password: 123321
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
